# Generated by Django 5.1.2 on 2025-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_duel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duel",
            name="is_active",
        ),
        migrations.AddField(
            model_name="duel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
