# Generated by Django 5.2.4 on 2025-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_duel_is_active_duel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
