# Generated by Django 5.2.4 on 2025-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_duel_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousePoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("Gryffindor", "Gryffindor"),
                            ("Hufflepuff", "Hufflepuff"),
                            ("Ravenclaw", "Ravenclaw"),
                            ("Slytherin", "Slytherin"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "House Point",
                "verbose_name_plural": "House Points",
            },
        ),
    ]
