# Generated by Django 5.2.4 on 2025-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_housepoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="duel",
            name="last_defender_spell",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="duel",
            name="last_spell_cast",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
