# Generated by Django 5.1.2 on 2025-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_duel_last_defender_spell_duel_last_spell_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="duel",
            name="last_attack_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
